### ISSUE TITLE
/account/getorder endpoint is not documented and not working

### ISSUE THREAD

**Issue by CherryDT** [AndrewBarba/bittrex-node#7]
I was looking for the right function for `/account/getorder`. It seems it exists as `order`, but it's not documented.

Furthermore, it doesn't work:

```
> await c.order('6b75e9e8-3a25-4920-9c19-ad8ac409a6f7')
TypeError: results is not iterable
    at BittrexClient.parseDates (/mnt/c/Users/david/proj/fox-exchange/node_modules/bittrex-node/src/bittrex-client.js:329:24)
    at BittrexClient.order (/mnt/c/Users/david/proj/fox-exchange/node_modules/bittrex-node/src/bittrex-client.js:238:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

...probably because it's not returning an array...

**Comment by AndrewBarba** [comment]
Sorry about that, fixed in 1.2.0 https://github.com/AndrewBarba/bittrex-node/releases/tag/1.2.0
